# Generated by Django 5.0.6 on 2024-07-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicioapp', '0007_admin_imagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='password',
        ),
    ]
